#!/usr/bin/env bash

# Define the path to your SSH config and hosts mapping file
ssh_config="$HOME/.ssh/config"

# Ensure the ssh_config exists
if [ ! -f "$ssh_config" ]; then
	tmux display-message -d 3000 "SSH config file not found"
	sleep 3
	exit 1
fi

# Use fzf to select a host
selected_host=$(awk '/^Host / && !/\*/ {print $2}' "$ssh_config" | fzf --height=40% --reverse --header="$fzf_header" --prompt="Type or select SSH host: ")

# Exit if no selection is made
if [[ -z $selected_host ]]; then
	echo "No host selected. Exiting."
	exit 0
fi

# Normalize the host name for session naming
selected_after_tr=$(echo "$selected_host" | tr '.-' '__')
echo $selected_after_tr
# tmux display-message -d 3000 "selected_after_tr = $selected_after_tr"

# If a tmux session with the desired name does not already exist, create it in detached mode
if ! tmux has-session -t=$selected_after_tr 2>/dev/null; then
	tmux new-session -s "$selected_after_tr" -d "ssh $selected_host"
fi

# Switch to the tmux session with the name derived from the selected directory
tmux switch-client -t $selected_after_tr
